language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - pip install codecov
  - python setup.py bdist_wheel
install:
  - pip install dist/cfnjsontoyaml-*
script: nosetests --with-coverage
matrix:
  allow_failures:
    - python: "3.4"
after_success:
  codecov
